# Utilisez une image Debian de base
FROM debian:latest

# Installer les dépendances requises pour Odoo
RUN apt-get update && \
    apt-get install -y git python3-pip build-essential wget \
        python3-dev libxml2-dev libxslt1-dev \
        libjpeg-dev libpq-dev libldap2-dev \
        libsasl2-dev node-less

# Télécharger et installer Odoo
RUN git clone https://www.github.com/odoo/odoo --depth 1 --branch 14.0 --single-branch /opt/odoo && \
    pip3 install -r /opt/odoo/requirements.txt

# Définir le répertoire de travail
WORKDIR /opt/odoo

# Exposer le port d'Odoo
EXPOSE 8069

# Démarrer Odoo
CMD ["./odoo-bin"]
