FROM debian:latest

RUN wget -O - https://nightly.odoo.com/odoo.key
RUN sudo gpg --dearmor -o /usr/share/keyrings/odoo-archive-keyring.gpg
RUN echo 'deb [signed-by=/usr/share/keyrings/odoo-archive-keyring.gpg] https://nightly.odoo.com/16.0/nightly/deb/ ./'
RUN sudo tee /etc/apt/sources.list.d/odoo.list
RUN apt-get update && sudo apt-get install adoo

# Exposer le port d'Odoo
EXPOSE 8069